### ISSUE TITLE
Authenticate accounts in API.php

### ISSUE THREAD

**Issue by luandnh** [goautodial/goAPIv2#38]
Somebody check goAPI.php in root folder.
Why do we count sum of result?
`110: $astDB->getOne("vicidial_users", "count(*) as sum");`
`111: $check_result = $astDB->count;`
If username or password is wrong, count(*) will be 0 and count of result will be 1.
Therefore, authentication in goAPI.php is almost pointless.

I edited that code in my company's project and realized that there would be a problem with the hash password.
    `68: $goPass = (isset($_REQUEST['log_pass']) ? $astDB->escape($_REQUEST['log_pass']) : $astDB->escape($_REQUEST['goPass']));`
	`87: $bcrypt = 0;`
`90: $pass = preg_replace("/\'|\"|\\\\|;| /", "", $goPass);`

`95: $passSQL = "pass='$pass'";`
	`if ($system_settings['pass_hash_enabled'] > 0) {`
		`if ($bcrypt < 1) {`
			`$pass_hash = encrypt_passwd($pass, $system_settings['pass_cost'], $system_settings['pass_key']);`
		`} else {$pass_hash = $pass;}`
		`$passSQL = "pass_hash='$pass_hash'";`
	`}`
You set the default bcrypt = 0 and check it. So all the passwords that are brought to you are hashed even if it has already been hashed (log_pass).
I think you should check if the password entered is log_pass or goPass. If it is log_pass, it is no longer necessary to hash because this is the data retrieved in the session data. If it is goPass, it will hash the password and continue processing.

This project is still really great.
If you need any assistance, please contact me via personal email:
luandnh1998@gmail.com

**Comment by demianb** [comment]
This needs to be updated. Encrypted passwords are now the new normal. 

The proper way to call the goAPI:

curl 'https://DOMAINNAME/goAPIv/goCampaigns/goAPI.php?goAction=goAddCampaign&goUser=goAPIuser&goPass=ENCRYPTEDPASSWORD&responsetype=json&campaign_id=12231977&campaign_name=CAMPAIGN_NAME&campaign_type=outbound&dial_prefix=CUSTOM&custom_prefix=9&dial_method=MANUAL&auto_dial_level=OFF&campaign_recording=NEVER&answering_machine_detection=8369&session_user=admin&user_group=ADMIN'

The encrypted value can be derived from the pass_hash column in the vicidial_users table under the asterisk database. Or you can use /var/www/html/bin/pass_hasher.php to generate the encrypted password.

**Comment by luandnh** [comment]
Sorry if my english is bad.

> This needs to be updated.

This means that you or the team will fix this file, or you mean that the way of calling api needs to be changed.

Because the current problem is the code at goAPI.php, I don't think calling API with `goPass = ENCRYPTEDPASSWORD` is a problem. If you call `goPass = ENCRYPTEDPASSWORD`, the code at goAPI.php will still encrypt it again. As a result, users' valid check is also wrong. The real problem lies in the code.

**Comment by demianb** [comment]
"This needs to be updated" means that we might have to remove the option of entering plain text passwords (since it's a security risk) and enforce encrypted passwords only.

It might seem to look as if it's double encrypting but its not. Try doing some API calls in your GOautodial server using encrypted passwords. If it's double encrypting, the API calls won't be successful.

> I think you should check if the password entered is log_pass or goPass. If it is log_pass, it is no longer necessary to hash because this is the data retrieved in the session data. If it is goPass, it will hash the password and continue processing.
