### ISSUE TITLE
Can't create campaign if there's not campaign.

### ISSUE THREAD

**Issue by Jonasfxh** [goautodial/goAPIv2#4]
After deleting all campaigns, the system show an error saying "API ERROR: No Available Data" and we don't have any button to create a new campaign.

Here's a image
![image](https://user-images.githubusercontent.com/8949219/69672904-73e4a500-106f-11ea-9f0e-038040be8dd0.png)

Expected result: The table should be empty, but the button for creating campaign should stay.

**Comment by wittie** [comment]
Hi,

We have created issue tracker for the said bug. Please monitor updates @ https://goautodial.org/issues/7745

Thanks

**Comment by wittie** [comment]
Hi,

Please update your server to fix the issue

Thanks

**Comment by Jonasfxh** [comment]
What I did to solve may scare a little. I downloaded the GoAutodial web project from github and re-install it again, drop the databases and I re-created them again.

That solved the problem. 

Note: I tried inserting some rows in the Campaign's table manually from SQL, but I have no idea how it reads the database to load the data on the site because it ignores what I had modified on the db directly.
